name: Build
on:
  push:

jobs:
  # Build job. Builds every demo app for Android with Buildozer
  build-android:
    name: Build Android [${{ matrix.demo-name }}]
    strategy:
      fail-fast: false
      matrix:
        demo-name: [kitchen_sink]
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1

  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: test_sample

    - name: Checkout Keystore repo
      uses: actions/checkout@v2
      with:
        repository: hemanta212/personal
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        ref: "refs/tags/vkivyapp"
        path: 'personal'

    - uses: actions/checkout@v2
      with:
        path: 'app'

    - run: |
        cd test_sample
        mkdir rel

        cd ${{ matrix.demo-name }}
        source ../../personal/credentials/keystores/.env
        export P4A_RELEASE_KEYSTORE=`readlink -f ../../personal/credentials/keystores/kivyapplicationkey.keystore`
        export P4A_RELEASE_KEYSTORE_PASSWD=$KEYSTORE_PASS
        export P4A_RELEASE_KEYALIAS_PASSWD=$KEYSTORE_PASS
        export P4A_RELEASE_KEYALIAS=kivykey

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        repository_root: test_sample
        workdir: ${{ matrix.demo-name }}

    - uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.project }}_armeabi-v7a-release.apk
        path: ${{ steps.buildozer.outputs.filename }}
