name: Build
on:
  push:


jobs:
  setup:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       project: ['hello_world']

   steps:
     - run: |
          sudo apt-get update
          sudo pip install --upgrade cython==0.28.6
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install build-essential ccache git libncurses5:i386 libstdc++6:i386 libgtk2.0-0:i386 libpangox-1.0-0:i386 libpangoxft-1.0-0:i386 libidn11:i386 python2.7 python2.7-dev python3-pip openjdk-8-jdk unzip zlib1g-dev zlib1g:i386
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install buildozer

     - name: Checkout Keystore repo
       uses: actions/checkout@v2
       with:
         repository: hemanta212/personal
         token: ${{ secrets.REPO_ACCESS_TOKEN }}
         ref: "refs/tags/vkivyapp"
         path: 'personal'

     - uses: actions/checkout@v2
       with:
         path: 'app'

     - run: |
          export PATH=$PATH:~/.local/bin/
          cd app
          mkdir rel

          cd ${{ matrix.project }}
          python --version
          python3 -m buildozer -v android release 
          mv bin/*.apk ../rel/${{ matrix.project }}_armeabi-v7a-release.apk 

     - uses: actions/upload-artifact@v1
       with:
         name: ${{ matrix.project }}_armeabi-v7a-release.apk
         path: app/rel/${{ matrix.project }}_armeabi-v7a-release.apk

  release:
    needs: setup
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
         path: 'app'

     - run: |
         cd app
         mkdir rel/

     - uses: actions/download-artifact@v1
       with:
         name: hello_world_armeabi-v7a-release.apk
         path: rel/

        
     - name: Release
       uses: softprops/action-gh-release@v1
       if: startsWith(github.ref, 'refs/tags/')
       with:
         files: |
             rel/hello_world_armeabi-v7a-release.apk
         body_path: app/CHANGELOG.txt
         draft: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
